# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def view_books(self):
        for book in self.books:
            print(book)

    def remove_book(self, book):
        if book in self.books:
            self.books.remove(book)
        else:
            print(f"{book} not found in the library.")
class MemberLibrary(Library):
    def __init__(self, member_name):
        super().__init__()
        self.member_name = member_name
        self.checked_out_books = []

    def view_checked_out_books(self):
        print(f"{self.member_name}'s Checked-Out Books:")
        for book in self.checked_out_books:
            print(book)

    def check_out_book(self, book):
        if book in self.books:
            self.checked_out_books.append(book)
            self.remove_book(book)
            print(f"{self.member_name} checked out {book}")
        else:
            print(f"{book} is not available in the library.")

    def return_book(self, book):
        if book in self.checked_out_books:
            self.checked_out_books.remove(book)
            self.add_book(book)
            print(f"{self.member_name} returned {book}")
        else:
            print(f"{self.member_name} doesn't have {book} checked out.")
# Create a library object
library = Library()

# Add books to the library
library.add_book("Book 1")
library.add_book("Book 2")
library.add_book("Book 3")

# View available books
print("Available Books:")
library.view_books()

# Remove a book from the library
library.remove_book("Book 2")

# Create a member library object
member_library = MemberLibrary("Abdul")

# John checks out a book
member_library.check_out_book("Book 1")
member_library.check_out_book("Book 4")

# View John's checked-out books
member_library.view_checked_out_books()

# John returns a book
member_library.return_book("Book 1")

# View available books after returning
print("Available Books:")
library.view_books()